--- #YAML:1.0
name:               MooseX-Role-Timer
version:            0.03
abstract:           Role for measuring elapsed Time
author:
    - Michael Langner (mila@cpan.org)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Moose:        1
    Test::More:   0.8
    Time::HiRes:  1
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
